### ISSUE TITLE
Bug: field 'sequence' is required but does not exist

### ISSUE THREAD

**Issue by markscherz** [iTaxoTools/DNAconvert#26]
Using Mac GUI version, I get the error "field 'sequence' is required" irrespective of whether data are pasted in the box or added as a .txt file through the Input File browser. There is no 'sequence' field to be filled out. Error stays no matter what combination of boxes are ticked. 
<img width="963" alt="Screenshot 2021-05-04 at 17 16 19" src="https://user-images.githubusercontent.com/46906676/117026898-720b2080-acfc-11eb-870f-978859bfe97d.png">

**Comment by necrosovereign** [comment]
From the screenshot it seems that the data doesn't have a header. You can prepend the line "seqid\tsequence" to your data and it should work.

For the tab format DNAconvert requires the first line to be a header with the names of the columns, e.g. "seqid\tspecies\tsequence".
Maybe the error message should be reformulated.

**Comment by markscherz** [comment]
Ah, okay, it is not clear anywhere in the software that a special heading is needed. I thought just pasting a tab-delimited table into the text box would work. I therefore recommend that this is stated explicitly somewhere on the interface. 
As a response behaviour to missing headers, it would be useful to have a prompt that says 'We noticed you did not provide a header.', followed by a set of dropdown boxes that allow you to identify the contents of the two or three columns in the tab-delimited file into each of the three categories

**Comment by mvences** [comment]
I would suggest one relatively simple option to deal with this. I agree the need for specific headers can be non-intuitive and confusing. But having additional pull-down menus etc. seems like an overkill solution. So I propose the following solution:
Add one additional sequence format. That would be "Tab-no headers". This format will just accept a format in which there are one or several tab-delimited fields, in which the last one is the sequence and all the ones preceding the sequence form the sequence name (will be concatenated with underscores if there is more than one field preceding the sequence).

In order to make this even more error-proof we could think about a set of simple rules to identify the field containing the sequence. I can imagine some stupid users pasting files with a variable number of tab-delimited fields in front of the sequence, or even with one or two "forgotten" tabs after the sequence. However, usually it should be easy to recognize what a DNA sequence is, there are several easy rules:
- The sequence will almost always be much longer than the content of all other fields (many more characters)
- The vast majority of sequence characters will be ACGTacgt-? (for now, the program is called "DNA"convert, so we can ignore the possibility of protein sequences.

So maybe, a filter can be implemented so that the programs looks up the string of characters in the last tab-delimited field, and if it complies with these rules it proceeds with the conversion, but if it encounters something strange, it looks for a sequence in the other fields. This may not work perfectly in the first implementation, but we can later try to refine it further.

**Comment by markscherz** [comment]
Agreed, this would be a nice option.
Possible values for DNA fields would be 
A T G C R Y M K S W B D H V N U - ? 
and all lowercase variants thereof (am I missing any?)
In some cases whole strings of pure N or - would be included in the DNA field as well, so I think just searching for ATGC will not be enough. So maybe just identify the field that only includes these characters? And probably only do it at the top of the file for convenience and assume the same column for the rest? Otherwise I can imagine this being quite a computationally intensive task if it is run on each row.
