### ISSUE TITLE
Add support for NeXML

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/DNAconvert#38]
NeXML is a format that encodes genetic sequences but also other kind of information in an XML-compatible format. As I will explain in a separate email, we will likely rely on NeXML for data exchange in TaxI3 and in other new tools such as Concordanceseeker. Therefore, my suggestion is to first start integrating NeXML support in DNAconvert which should be rather easy, and will allow gaining some insights and experience with this format, before integrating it in more complex ways in the other programs.

The NeXML original code (also for Python) is included in this GitHub repository:
https://github.com/nexml/nexml

NeXML support is included in the Dendropy library, so it should be relatively easy to implement it if integrating Dendropy into DNAconvert.

Note that Dendropy also includes support for Nexus, but I am not sure how good its Nexus parser is. If Dendropy is added to DNAconvert, then it might be worth considering to also change the Nexus parsing, and use Dendropy for it. But if NeXML support can be added without Dendropy, then it is also fine.

**Comment by necrosovereign** [comment]
I'm not sure if I understand NeXML correctly. I tried converting a Fasta into NeXML using:
```python
import dendropy
data = dendropy.DNACharacterMatrix.get(path="sequence_example.fas", schema="fasta")
[sequence_example.txt](https://github.com/iTaxoTools/DNAconvert/files/7870466/sequence_example.txt)

data.write_to_path("sequence_example.xml", "nexml")
```
and it turned 4 kB Fasta file into a 196 kB NeXML file.

I think that the reason for this is that in the NeXML file, every nucleotide is represented by line like this:
```xml
                <cell char="d2139" state="d10"/>
```
This seems wasteful. Maybe there is a way to make dendropy to represent DNA sequences as sequences of characters or bytes?

Here is the file I used (I changed the extension to '.txt', because GitHub didn't upload with the '.fas' extension):
[sequence_example.txt](https://github.com/iTaxoTools/DNAconvert/files/7870467/sequence_example.txt)

**Comment by mvences** [comment]
I think this is probably correct. NexML is an extremely verbose, "inflated" format. I have myself no experience with NeXML. Maybe one option would be to ask Jeet Sukumaran (developer of Dendropy and co-developer of NeXML) if the transformation is correct. Could you send me by email both the Fasta file and the resulting (converted) NeXML file, I can then forward it to Jeet for checking.
